version: "3.7"

services:
  database:
    image: postgres
    container_name: urentcars-database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: urentcars-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urentcars-network

  app:
    build: .
    container_name: urentcars-backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - urentcars-network
    depends_on:
      - database
    env_file:
      - .env-docker

volumes:
  pgdata: {}

networks:
  urentcars-network:
    driver: bridge
